export interface StyleItem {
  name: string;
  cover: string;
  categories: string[];
}

export const styleCategories = [
  "全部", "国风", "IP风格", "日系风格", "插画风格", "可爱Q版", "欧美风格", "韩系", "立体风格",
] as const;

export type StyleCategory = (typeof styleCategories)[number];

export const styleItems: StyleItem[] = [
  { name: "三渲二", cover: "/styles/D99vbXB1doIKSXx6OTccNkJJnFf.webp", categories: ["IP风格", "日系风格"] },
  { name: "都市言情", cover: "/styles/mkxa9z1417ad447d576c9c37.webp", categories: ["插画风格", "韩系"] },
  { name: "美式3D", cover: "/styles/mmybnw1v2c487724498b2453.webp", categories: ["IP风格", "欧美风格", "立体风格"] },
  { name: "JoJo", cover: "/styles/mmybe6qmf173657b050d2bbe.webp", categories: ["IP风格", "日系风格"] },
  { name: "藤本树", cover: "/styles/mkuncm4g92c8d45814db87af.webp", categories: ["日系风格", "插画风格"] },
  { name: "3D国创", cover: "/styles/mmybeumx7e10035f533075cd.webp", categories: ["国风", "立体风格"] },
  { name: "女频漫画", cover: "/styles/mkunb6x7ddab02a8d5b9a34e.webp", categories: ["插画风格", "韩系"] },
  { name: "韩系都市", cover: "/styles/mmybjstla7dc1bde705f24d4.webp", categories: ["韩系"] },
  { name: "治愈Q萌", cover: "/styles/mmybh6q1cbd5db23c9e5646a.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "2D漫剧", cover: "/styles/mmybj4fx2c784d03004b2e52.webp", categories: ["国风"] },
  { name: "木叶村", cover: "/styles/mmybg10q3003e3aee2a73990.webp", categories: ["IP风格", "日系风格"] },
  { name: "粘土玩具", cover: "/styles/mmybk4gm3fa358366f1f6388.webp", categories: ["插画风格", "可爱Q版", "立体风格"] },
  { name: "吉卜力", cover: "/styles/mkwezy4rab0b3437df8ddcb8.webp", categories: ["IP风格", "日系风格", "插画风格"] },
  { name: "莱卡定格动画", cover: "/styles/mkuqiy61c4593d8320f2c552.webp", categories: ["IP风格", "立体风格"] },
  { name: "美式喜剧", cover: "/styles/mkulcq7n6fecb7d4e34cbfbd.webp", categories: ["IP风格", "欧美风格", "立体风格"] },
  { name: "方块世界", cover: "/styles/mkuk6br51c399956c426fcec.webp", categories: ["立体风格"] },
  { name: "辛逝季-芙莉莲", cover: "/styles/mkxi85yydc9581d8bfd6d637.webp", categories: ["IP风格", "日系风格"] },
  { name: "草帽团", cover: "/styles/mmybsfeq4036765223332db0.webp", categories: ["IP风格", "日系风格"] },
  { name: "尸魂界-死神", cover: "/styles/mmybl79mbbe27f74ddf7de2a.webp", categories: ["IP风格", "日系风格"] },
  { name: "辛普森", cover: "/styles/mkuk69rg23acb61c44e3bdd3.webp", categories: ["IP风格", "欧美风格"] },
  { name: "吊带袜女孩", cover: "/styles/mmyblxkbb82e37e633118627.webp", categories: ["日系风格"] },
  { name: "空灵哥特", cover: "/styles/mmybmbca4fd3c2ae4444e45e.webp", categories: ["日系风格", "插画风格"] },
  { name: "国风水墨", cover: "/styles/mmybot0eaa74e8f640da0bf4.webp", categories: ["国风"] },
  { name: "怪萌墨线", cover: "/styles/mkwayvnc4532b2f0cc0590ca.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "恐怖悬疑", cover: "/styles/mmybocqubbd61d622a3e5d2d.webp", categories: ["国风"] },
  { name: "油画釉光", cover: "/styles/mkxf2ko66a748af265442f95.webp", categories: ["日系风格", "插画风格"] },
  { name: "Q版3D", cover: "/styles/mmybppt3e8ba6a862e3b3b6b.webp", categories: ["可爱Q版", "立体风格"] },
  { name: "温馨彩绘", cover: "/styles/WTGkbuLdEoKK7XxyNcEcHhYpnsb.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "潮流都市", cover: "/styles/mkpfuv0a456fd5aba588a132.webp", categories: ["插画风格", "韩系"] },
  { name: "锈湖", cover: "/styles/mmybvam754a25cadecc0d899.webp", categories: ["IP风格"] },
  { name: "低饱和平涂手绘", cover: "/styles/mkwb3vm9a13286ad436fd3ce.webp", categories: ["日系风格", "插画风格"] },
  { name: "复古掌机", cover: "/styles/mkuk68mn082e8496d9d6e875.webp", categories: ["IP风格"] },
  { name: "蚀刻光影", cover: "/styles/mkqnczcwf5b1063b03da4ef5.webp", categories: ["插画风格"] },
  { name: "80s年代", cover: "/styles/mmybpcbue4bc4f173118ebb1.webp", categories: ["日系风格", "插画风格"] },
  { name: "名侦探阿楠", cover: "/styles/RIZdbfLpqoZS92x1WUpcVASanMR.webp", categories: ["IP风格", "日系风格"] },
  { name: "可爱马卡龙", cover: "/styles/ZEvtb1LN7oh1ZFxOBoZcI9XrnJe.webp", categories: ["日系风格", "插画风格", "可爱Q版"] },
  { name: "Q版草绘", cover: "/styles/mkpmm86fa501cf818982f9e8.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "空灵现实", cover: "/styles/mkqoz6ao35eef835200ac490.webp", categories: ["韩系"] },
  { name: "柔光平涂", cover: "/styles/mkpmmury2f7a50dce448e02e.webp", categories: ["日系风格", "插画风格"] },
  { name: "美式颗粒", cover: "/styles/mkws2nb5b0246e840a01f1df.webp", categories: ["插画风格", "可爱Q版", "欧美风格"] },
  { name: "邪魅琉璃", cover: "/styles/mkqk3oa00f6107fdcfb91660.webp", categories: ["插画风格"] },
  { name: "龙族传说", cover: "/styles/mmybt3zfeeef23fdfdf986a8.webp", categories: ["IP风格", "日系风格"] },
  { name: "像素", cover: "/styles/mkukao87d56f62ca6ed93cf4.webp", categories: ["可爱Q版"] },
  { name: "复古彩光", cover: "/styles/mkqk3qbv9a3caa8c4f278e5b.webp", categories: ["可爱Q版", "欧美风格"] },
  { name: "哥特都市涂鸦", cover: "/styles/mkpmlyh6278de641d9bc3312.webp", categories: ["插画风格", "欧美风格"] },
  { name: "动森", cover: "/styles/mkuls64icde10e6c452e6cc6.webp", categories: ["IP风格", "可爱Q版"] },
  { name: "乐高", cover: "/styles/JmhLb8ESCo2dvXxP9L6cSqGEnOe.webp", categories: ["IP风格", "可爱Q版", "立体风格"] },
  { name: "朦胧暖色速写", cover: "/styles/VSrPb4cIyokcqXxDBHRcoOHxnDd.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "粗犷硬边赛璐璐", cover: "/styles/mmybs6kp164cdd9e40ce8ab0.webp", categories: ["插画风格", "欧美风格"] },
  { name: "扁平涂鸦", cover: "/styles/mkxfrhubae3af0fc339dd9cc.webp", categories: ["插画风格", "可爱Q版", "欧美风格"] },
  { name: "治愈柔和Q版", cover: "/styles/mkwb7jhib08b1cadc218c40b.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "厚涂柔光怀旧", cover: "/styles/mkpmsgstea7ac0c6941802b1.webp", categories: ["插画风格"] },
  { name: "彩色排线手绘", cover: "/styles/Tb6Fbzadho4pPtxdKaJcXmkqnMh.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "比奇堡", cover: "/styles/mkum3m3c627db6bdfc128c66.webp", categories: ["IP风格", "插画风格", "可爱Q版"] },
  { name: "怀旧胶片线条", cover: "/styles/VlTYbh4dCo144wxoydccAihInJc.webp", categories: ["插画风格", "欧美风格"] },
  { name: "迷幻复古都市", cover: "/styles/mkuudok2ebd5c5a77f879c02.webp", categories: ["插画风格", "欧美风格"] },
  { name: "光栅像素艺术", cover: "/styles/mkxatzfhb2be33bee8921ea5.webp", categories: ["欧美风格"] },
  { name: "冷静感线条", cover: "/styles/mkuuecljc1a99f2f5362e712.webp", categories: ["插画风格"] },
  { name: "粗线块面卡通", cover: "/styles/mkx9dxowd8099d37dbb58bec.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "复杂线条都市漫", cover: "/styles/LdInbDGEzoxzYSxChrRc22PDnIf.webp", categories: ["插画风格"] },
  { name: "通透柔光厚涂", cover: "/styles/mkqhi8lq8a4ce5381447e288.webp", categories: ["插画风格"] },
  { name: "怪诞哥特卡通", cover: "/styles/mkuqj00y32264dadeed0f187.webp", categories: ["IP风格", "插画风格", "欧美风格"] },
  { name: "扁平图形设计", cover: "/styles/mkul501v6afb03ea281c97d8.webp", categories: ["IP风格", "插画风格", "可爱Q版"] },
  { name: "童趣蜡笔插画", cover: "/styles/mkpfuutbc86cc26ade71bbd2.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "可爱抽象涂鸦", cover: "/styles/mkqozcy14fe63b4b15081083.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "莫兰迪水粉手绘", cover: "/styles/mkuniuaj186063ef0ece0855.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "诡萌幻想绘本", cover: "/styles/Gl15b65bto9hahxKIhmcPDCLn9B.webp", categories: ["插画风格"] },
  { name: "蜡笔小新", cover: "/styles/mkwcfepfec374199e0ab4a50.webp", categories: ["IP风格", "可爱Q版"] },
  { name: "火柴人", cover: "/styles/mmybtk4x4877dc7af2a34430.webp", categories: ["可爱Q版"] },
  { name: "清新童趣Q版", cover: "/styles/mkuuiey3e788a8c6df7064b4.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "甜美粉彩", cover: "/styles/mkxaug91137532af057247e6.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "粗犷墨线", cover: "/styles/mkwd4klr06fde96dd2022750.webp", categories: ["插画风格", "欧美风格"] },
  { name: "炭笔暗黑朋克", cover: "/styles/mkpfzzkv985dd21283edce00.webp", categories: ["插画风格", "欧美风格"] },
  { name: "欧漫概念艺术", cover: "/styles/JFrpbrikRoAKE9xYRjXchD1mn3c.webp", categories: ["插画风格", "欧美风格"] },
  { name: "复古梦幻赛璐璐", cover: "/styles/mkqhnpjge2251f39e142dcf9.webp", categories: ["日系风格", "插画风格"] },
  { name: "通透光影厚涂", cover: "/styles/mkw218nd0d2781089f3baec6.webp", categories: ["插画风格"] },
  { name: "美式粗线漫画", cover: "/styles/mkw1zv8782e6f4bc1dfd65df.webp", categories: ["插画风格", "可爱Q版", "欧美风格"] },
  { name: "魅惑哥特霓虹", cover: "/styles/mkw1z6ekc8de82bf0ebcb7f6.webp", categories: ["插画风格", "欧美风格"] },
  { name: "蒸汽波神话糖果治愈系", cover: "/styles/Ab07bfcWaor0TdxVE16cQPLAn9g.webp", categories: ["日系风格", "插画风格"] },
  { name: "水粉童书插画", cover: "/styles/UfjCbSDJqoSOYQxP4UgcUyM2nLh.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "都市潮漫硬边撞色", cover: "/styles/mkpfjd20f5289ede59766e8a.webp", categories: ["插画风格"] },
  { name: "浮世绘超现实主义", cover: "/styles/LSe4baHg1o0OtWxn8MnclhSenBc.webp", categories: ["插画风格"] },
  { name: "柔光浪漫水彩笔触", cover: "/styles/Q9UtbOYX9oOgLLxH0jpcqTPjnce.webp", categories: ["插画风格"] },
  { name: "治愈冒险漫画", cover: "/styles/PoLvbe7mDoUX32xAdmoculFWn9e.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "日式少女漫", cover: "/styles/BMhabUfCcoupuZxMtttcA3A5n6e.webp", categories: ["日系风格", "插画风格"] },
  { name: "毛绒玩具质感", cover: "/styles/mkwcjalj8c866285c4eff41d.webp", categories: ["可爱Q版", "立体风格"] },
  { name: "空气彩铅", cover: "/styles/mmybu08330121a9eb439716e.webp", categories: ["日系风格", "插画风格", "可爱Q版"] },
  { name: "光影平涂", cover: "/styles/RsLqbg2YUodJAHxEFi7cIg2xnJd.webp", categories: ["插画风格"] },
  { name: "轻复古水彩", cover: "/styles/mkuup7nref5d7c81ff900205.webp", categories: ["插画风格"] },
  { name: "卡通平涂漫画", cover: "/styles/mkxfs6waa8c92289e5ab383f.webp", categories: ["插画风格"] },
  { name: "东方淡彩", cover: "/styles/LlgvblKveo1BJQxVrBEcsd6TnVf.webp", categories: ["插画风格"] },
  { name: "戏剧光影水彩色块", cover: "/styles/mkqnwh294d19420d6d7cd7f1.webp", categories: ["插画风格"] },
  { name: "奇幻平涂", cover: "/styles/PmSrbFZHwo8iDkxGaQqcghyxnse.webp", categories: ["插画风格"] },
  { name: "史努比", cover: "/styles/mkum7hgea3b54a55b4e1e801.webp", categories: ["IP风格", "可爱Q版"] },
  { name: "治愈童趣颗粒彩铅", cover: "/styles/mkpg2kb9c850380b1fd08d2e.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "粗线潮流Q版", cover: "/styles/Uei5bDp6ro3HcjxCOsPchZ0GnYd.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "颗粒粉彩童话风", cover: "/styles/W1LybifPQogy3GxgwZaccUvon3e.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "抒情柔光线条", cover: "/styles/PoF8bT7zzoTeIExL9hhcWFIDn6g.webp", categories: ["插画风格"] },
  { name: "文艺复兴古典画", cover: "/styles/mkuqiklr7caab33bc021b7c8.webp", categories: ["欧美风格"] },
  { name: "朦胧印象派", cover: "/styles/OxzNbTTQpovtyZxyHKkccrzWnpg.webp", categories: ["插画风格"] },
  { name: "矢量扁平色块", cover: "/styles/YbTLbVobmoOJtDxwhwjcl9Upnrg.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "质朴蜡笔", cover: "/styles/DUHgbhCscoRdiQxPTPScyUIKnKb.webp", categories: ["插画风格"] },
  { name: "粗糙颗粒肌理版画", cover: "/styles/VKtQbFS5ko2R2ixdzYkc0k0kndg.webp", categories: ["插画风格"] },
  { name: "甜美可爱复古波普", cover: "/styles/UfGvbL4tzooPH1xMiXucZcgBnzd.webp", categories: ["插画风格"] },
  { name: "波普印刷", cover: "/styles/U7P6bd3OioaJTQxIyRUcCPgSnHf.webp", categories: ["插画风格"] },
  { name: "奶油色绘本", cover: "/styles/mkqkethf9a404908a35f9515.webp", categories: ["插画风格"] },
  { name: "表现主义儿童涂鸦", cover: "/styles/CQ85b6B9Aom8T6x3sEKcZbk9njg.webp", categories: ["插画风格", "欧美风格"] },
  { name: "古典戏剧情绪光影", cover: "/styles/KA5Mbaz7xo5PPCxhov8cGiYNnoB.webp", categories: ["插画风格"] },
  { name: "五零年代", cover: "/styles/mmybujyr63b0ee7d94ad1de9.webp", categories: ["插画风格", "欧美风格"] },
  { name: "彩铅素描插画", cover: "/styles/mkpg6n68115d57837694d12d.webp", categories: ["插画风格"] },
  { name: "温暖治愈Q版", cover: "/styles/mmybuzhd72fe61168eebc81e.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "怀旧电影感氛围光影", cover: "/styles/mkxftaoia2e93e27b0d16602.webp", categories: ["插画风格"] },
  { name: "墨线卡通", cover: "/styles/mkpmxyp765a2948be2746fe3.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "粗线活力动感卡通", cover: "/styles/mmybvjz9baf172c5b769ec21.webp", categories: ["插画风格", "欧美风格"] },
  { name: "虹彩梦幻治愈水彩", cover: "/styles/DtMZbAqqVodpCfxvTLYcLNsXnsg.webp", categories: ["插画风格"] },
  { name: "童趣速写", cover: "/styles/mkul5vcicb2ef8c220c69522.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "复古日式", cover: "/styles/mkul8sll5addfb1bedc34569.webp", categories: ["日系风格", "插画风格"] },
  { name: "复古线条都市", cover: "/styles/mkqkhz6qc77a2e71b4033f6c.webp", categories: ["插画风格"] },
  { name: "硬边萌系赛璐璐", cover: "/styles/mkwdcx1s7b993b46b7e58dcd.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "东方古典装饰", cover: "/styles/mkum7oe8a48a1a8aa88dc9b9.webp", categories: ["日系风格", "插画风格"] },
  { name: "折纸艺术", cover: "/styles/mkum7hh5a733ac64eceeb24e.webp", categories: ["可爱Q版", "立体风格"] },
  { name: "粗线超级Q版", cover: "/styles/mmybvtivdf6a8e3a9cd77239.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "高对比硬边缘图形", cover: "/styles/mkxau7ydcaa95a44014e2362.webp", categories: ["插画风格", "欧美风格"] },
  { name: "柔和光影厚涂卡通", cover: "/styles/mkw233ky5bf2684c2d441b9e.webp", categories: ["插画风格"] },
  { name: "棱镜故障艺术", cover: "/styles/mkuns5s483c2b160368e963f.webp", categories: ["插画风格", "欧美风格"] },
  { name: "高能动感卡通", cover: "/styles/mkqkitmx62e50aeec3988c27.webp", categories: ["插画风格", "欧美风格"] },
  { name: "唯美柔光辐射", cover: "/styles/mkxh36ck0491342f8835854e.webp", categories: ["插画风格"] },
  { name: "唯美清新通透", cover: "/styles/DpHhbDLFloG4e9xi840caDvXnue.webp", categories: ["插画风格"] },
  { name: "梦幻线条怪诞", cover: "/styles/mkqhtpwg7ceeace6c634d8f8.webp", categories: ["插画风格"] },
  { name: "发光线条柔光", cover: "/styles/mkpn716q7b1f679b4db277c4.webp", categories: ["插画风格"] },
  { name: "生动水彩图形", cover: "/styles/mmybw2zl046a057b6b399ed1.webp", categories: ["插画风格"] },
  { name: "柔光原画厚涂", cover: "/styles/mkpn5ov7efa131992d8d59d8.webp", categories: ["插画风格"] },
  { name: "通透光泽马卡龙", cover: "/styles/mmybx8pz2ab0ab33199c41ea.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "复古赛璐璐怀旧动画", cover: "/styles/mkunv2iw6df83631b64d47f6.webp", categories: ["插画风格"] },
  { name: "简约扁平手绘卡通", cover: "/styles/mkpn6d7l4494b4c78a516cb2.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "单色排线素描", cover: "/styles/ZIOdbHSQ5oMRQyxRPwmcG8jdnog.webp", categories: ["插画风格"] },
  { name: "风格化撞色赛博", cover: "/styles/mkqkpyfkb24b9dc2cede99f2.webp", categories: ["插画风格", "欧美风格"] },
  { name: "极简色块复古波普", cover: "/styles/mkqkqfp16428a828231d6753.webp", categories: ["插画风格", "欧美风格"] },
  { name: "美式肌肉讽刺卡通", cover: "/styles/mkqhxe7e65944f1f0e27f7e0.webp", categories: ["插画风格", "欧美风格"] },
  { name: "经典美式漫画", cover: "/styles/mkqi1i099d6c9ecf96798868.webp", categories: ["插画风格", "欧美风格"] },
  { name: "清新水彩墨线", cover: "/styles/mkway93n23b85234fcbb11ad.webp", categories: ["插画风格"] },
  { name: "Q萌马克笔着色", cover: "/styles/mkpn8poobd7e1f5f0bc4f1ac.webp", categories: ["插画风格", "可爱Q版"] },
  { name: "褪色颗粒怀旧", cover: "/styles/mkqi2v7idb063db949514417.webp", categories: ["插画风格"] },
  { name: "游戏CG", cover: "/styles/Hk34bCaquoAGUmxtaJNcbd4Nn8b.webp", categories: ["立体风格"] },
  { name: "3D乙游", cover: "/styles/mn5shxfg290e0e82234b66c1.webp", categories: ["国风", "IP风格", "立体风格"] },
  { name: "南方公园", cover: "/styles/mmycntwh6c7d01ff561bf879.webp", categories: ["IP风格", "欧美风格"] },
  { name: "欧美CG", cover: "/styles/PypubOSv5oKiKBxpe9ocyyIynkg.webp", categories: ["欧美风格", "立体风格"] },
];
